version: '3'
services:
  web:
    build: .
    #restart: always SOLAMENTE EN DESARROLLO SE DEJA COMENTADO ESTA LINEA
    environment: 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
    - '5000:5000'
    container_name: fastapi
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-http.rule=Host(`api.luiscontreras.xyz`)
      - traefik.http.routers.app-http.tls=true
      - traefik.http.routers.app-http.tls.certresolver=letsencrypt    
  database:
    image: mongo:5.0.2
    #restart: always SOLAMENTE EN DESARROLLO SE DEJA COMENTADO ESTA LINEA
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
    - '27017:27017'
    container_name: mongodb
    volumes: 
    - /root/dockerVolumes/dockerVolumes/mongo5:/data/db
  traefik:
    image: traefik:v2.3
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/traefik/traefik.toml:/etc/traefik/traefik.toml
      - traefik-public-certificates:/certificates

volumes:
  traefik-public-certificates:  